---
- hosts: all
  tasks:
    - name: 'INSTALA PACORES DE DEPENDENCIA OPERACIONAL'
      apt:
        name: "{{ item }}"
        state: latest
      become: yes
      with_items:
        - php
        - apache2
        - libapache2-mod-php
        - php-mysql
        - php-curl
        - php-gd
        - php-xml
        - php-mbstring
        - php-xmlrpc
        - php-zip
        - php-soap
        - php-intl
        - python3-pymysql
        #- php5-mcrypt
        - mysql-server

      
    - name: "CRIANDO O BANCO MYSQL"
      mysql_db:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: wordpress_db
        state: present
      become: yes

    - name: Create database user with password and all database privileges and 'WITH GRANT OPTION'
      mysql_user:
        login_user: root
        name: wordpress_user
        password: 12345
      priv: 'wordpress_db.*:ALL'
      state: present  

