---
- hosts: database

  handlers:
    - name: "RESTART-MYSQL"
      service:
        name: 'mysql'
        state: 'restarted'
      become: yes

  tasks:
    - name: 'INSTALA PACOTES DE BANCO DE DADOS MYSQL DEPENDENCIA OPERACIONAL'
      apt:
        name: "{{ item }}"
        state: latest
      become: yes
      with_items:
        - python3-pymysql
        - mysql-server

    - name: "CRIANDO O BANCO MYSQL"
      mysql_db:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: wordpress_db
        state: present
      become: yes

    - name: "CRIANDO O USUSARIO"
      mysql_user:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        #login_user: root
        name: wordpress_user
        password: 12345
        priv: 'wordpress_db.*:ALL'
        state: present    
        host: "{{ item }}"  
      loop:
        - '127.0.0.1' 
        - 'localhost'
        - '192.168.56.40'
      become: yes

    - name: "COPIANDO O ARQUIVO MY.CNF DO PROJETO PARA O HOST DE BANCO DESTINO"
      copy:
        src: 'files/my.cnf'
        dest: '/etc/mysql/mysql.conf.d/mysqld.cnf'
        remote_src: no
      become: true
      notify:
        - RESTART-MYSQL



- hosts: wordpress

  handlers:
    - name: "RESTART APACHE"
      service:
        name: 'apache2'
        state: 'restarted'      
      become: yes

  tasks:
    - name: 'INSTALA PACORES DO APACHE E DO PHP DE DEPENDENCIA OPERACIONAL'
      apt:
        name: "{{ item }}"
        state: latest
      become: yes
      loop:
        - php
        - apache2
        - libapache2-mod-php
        - php-mysql
        - php-curl
        #- php-gd
        - php-xml
        - php-mbstring
        - php-xmlrpc
        - php-zip
        - php-soap
        - php-intl
        #- python3-pymysql
        #- php5-mcrypt
        #- mysql-server

    - name: " BAIXA O ARQUIVO DE INSTALAÇÃO DO WORDPRESS "
      ansible.builtin.get_url:
        url: "https://wordpress.org/latest.tar.gz"
        dest: "/tmp/wordpress.tar.gz"

    - name: "DESCOMPACTANDO O ARQUIVO"        
      unarchive:
        src: "/tmp/wordpress.tar.gz"
        dest: "/var/www/"
        remote_src: yes # se caso o arquivo descompactado estiver na máquina target ( ou seja a máquina que o ansible está aplicando as mudanças)
      become: yes


    - name: "COPIANDO O ARQUIVO DE UMA LOCALIZAÇÃO"
      copy:
        src: '/var/www/wordpress/wp-config-sample.php'
        dest: '/var/www/wordpress/wp-config.php'
        remote_src: yes
      become: yes
      
    - name: "CONFIGURANDO O ARQUIVO DE CONFIGURAÇÃO DO WORDPRESS COM O MODULO REPLACE"
      replace:
        path: '/var/www/wordpress/wp-config.php'
        regexp: "{{ item.regex }}"
        replace: "{{ item.value }}"
        #backup: yes
      loop:
        - {regex: 'database_name_here', value: 'wordpress_db'}
        - {regex: 'username_here', value: 'wordpress_user'}
        - {regex: 'password_here', value: '12345'}
        - {regex: 'localhost', value: '192.168.56.42'}
      become: yes

    - name: "CONFIGURA APACHE PARA SERVIR O WORDPRESS"
      copy:
        src: 'files/000-default.conf'
        dest: '/etc/apache2/sites-available/000-default.conf'
      # como o arquivo não está na máquina alvo, está na nossa máquina de controle, não vamos usar o remote_src
      become: yes
      notify:
        - RESTART APACHE



    


    